### PR TITLE
[MemoryDemo] Fix build issue(#37347) + code refactoring

### PR DESCRIPTION
**Pull request by olegoid**
* Migrate before/after samples to unified
* Code refactoring
* Fix build issues - [#37347](https://bugzilla.xamarin.com/show_bug.cgi?id=37455)

@conceptdev since this sample accompanies [this guide](https://developer.xamarin.com/guides/ios/deployment,_testing,_and_metrics/walkthrough_Apples_instrument/) could you assign somebody from Docs team to review this PR?

### CODE REVIEW

**Comment by conceptdev** [comment]
@olegoid the **/before/** sample does not run at all - I presume that `UICollectionView` has gotten smarter in new versions of iOS, and bad code that used to work now fails -- however the solution should still compile and run.

1) collection view fails if `collectionView.DequeueReusableCell` isn't called



2) cell needs proper constructor for it to work



3) the 'commented out' code that helps customers fix the problem contains *Classic* types, so when they uncomment it has compiler errors



Do you want me to fix these problems in the branch?

**Comment by olegoid** [comment]
Thanks for review @conceptdev, I'll fix issues in "before" sample too.

Do you think it make sense to merge "before" and "after" samples into one project with two separate build configurations for _Before_ and _After_? It would  be much easier to maintain and use as a guide reference. Instead of switching between two projects with the same reader will select needed build config.

**Comment by conceptdev** [comment]
The only down-side with using build configurations is that we need them for _all_ options (ie. debug and release, sim & device). In particular this sample is intended to demonstrate memory leaks and fixes, which is done with *Instruments*. You really need to do this on a device - simulator memory isn't a good indicator of "real life". Basically we just need before & after configs for the iPhone build configs as well.

**Comment by olegoid** [comment]
@conceptdev I added device configs as well.

**Comment by olegoid** [comment]
Ready!

**Pull request merged**
